# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/grpc/ydb_backup_v1.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kikimr.public.api.protos import ydb_backup_pb2 as kikimr_dot_public_dot_api_dot_protos_dot_ydb__backup__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kikimr/public/api/grpc/ydb_backup_v1.proto',
  package='Ydb.Backup.V1',
  syntax='proto3',
  serialized_pb=_b('\n*kikimr/public/api/grpc/ydb_backup_v1.proto\x12\rYdb.Backup.V1\x1a)kikimr/public/api/protos/ydb_backup.proto2b\n\rBackupService\x12Q\n\x0c\x43reateBackup\x12\x1f.Ydb.Backup.CreateBackupRequest\x1a .Ydb.Backup.CreateBackupResponseB\x1a\n\x18\x63om.yandex.ydb.backup.v1b\x06proto3')
  ,
  dependencies=[kikimr_dot_public_dot_api_dot_protos_dot_ydb__backup__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\030com.yandex.ydb.backup.v1'))

_BACKUPSERVICE = _descriptor.ServiceDescriptor(
  name='BackupService',
  full_name='Ydb.Backup.V1.BackupService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=104,
  serialized_end=202,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateBackup',
    full_name='Ydb.Backup.V1.BackupService.CreateBackup',
    index=0,
    containing_service=None,
    input_type=kikimr_dot_public_dot_api_dot_protos_dot_ydb__backup__pb2._CREATEBACKUPREQUEST,
    output_type=kikimr_dot_public_dot_api_dot_protos_dot_ydb__backup__pb2._CREATEBACKUPRESPONSE,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_BACKUPSERVICE)

DESCRIPTOR.services_by_name['BackupService'] = _BACKUPSERVICE

# @@protoc_insertion_point(module_scope)
