# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/draft/streaming.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kikimr.public.api.protos import ydb_operation_pb2 as kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2
from kikimr.streaming.libs.control_plane.proto.public import control_plane_pb2 as kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kikimr/public/api/protos/draft/streaming.proto',
  package='Streaming',
  syntax='proto3',
  serialized_options=b'\n\024com.yandex.StreamingB\017StreamingProtos\370\001\001',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n.kikimr/public/api/protos/draft/streaming.proto\x12\tStreaming\x1a,kikimr/public/api/protos/ydb_operation.proto\x1a\x44kikimr/streaming/libs/control_plane/proto/public/control_plane.proto\"\x8f\x01\n\x13InstallQueryRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12=\n\x07request\x18\x02 \x01(\x0b\x32,.NStreams.NControlPlane.TInstallQueryRequest\"D\n\x14InstallQueryResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.Operation\"\x8d\x01\n\x12\x44\x65leteQueryRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12<\n\x07request\x18\x02 \x01(\x0b\x32+.NStreams.NControlPlane.TDeleteQueryRequest\"C\n\x13\x44\x65leteQueryResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.Operation\"\x8d\x01\n\x12ListQueriesRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12<\n\x07request\x18\x02 \x01(\x0b\x32+.NStreams.NControlPlane.TListQueriesRequest\"C\n\x13ListQueriesResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.Operation\"\x91\x01\n\x14\x44\x65scribeQueryRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12>\n\x07request\x18\x02 \x01(\x0b\x32-.NStreams.NControlPlane.TDescribeQueryRequest\"E\n\x15\x44\x65scribeQueryResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.OperationB*\n\x14\x63om.yandex.StreamingB\x0fStreamingProtos\xf8\x01\x01\x62\x06proto3'
  ,
  dependencies=[kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2.DESCRIPTOR,kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2.DESCRIPTOR,])




_INSTALLQUERYREQUEST = _descriptor.Descriptor(
  name='InstallQueryRequest',
  full_name='Streaming.InstallQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Streaming.InstallQueryRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Streaming.InstallQueryRequest.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=178,
  serialized_end=321,
)


_INSTALLQUERYRESPONSE = _descriptor.Descriptor(
  name='InstallQueryResponse',
  full_name='Streaming.InstallQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Streaming.InstallQueryResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=323,
  serialized_end=391,
)


_DELETEQUERYREQUEST = _descriptor.Descriptor(
  name='DeleteQueryRequest',
  full_name='Streaming.DeleteQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Streaming.DeleteQueryRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Streaming.DeleteQueryRequest.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=394,
  serialized_end=535,
)


_DELETEQUERYRESPONSE = _descriptor.Descriptor(
  name='DeleteQueryResponse',
  full_name='Streaming.DeleteQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Streaming.DeleteQueryResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=537,
  serialized_end=604,
)


_LISTQUERIESREQUEST = _descriptor.Descriptor(
  name='ListQueriesRequest',
  full_name='Streaming.ListQueriesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Streaming.ListQueriesRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Streaming.ListQueriesRequest.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=607,
  serialized_end=748,
)


_LISTQUERIESRESPONSE = _descriptor.Descriptor(
  name='ListQueriesResponse',
  full_name='Streaming.ListQueriesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Streaming.ListQueriesResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=750,
  serialized_end=817,
)


_DESCRIBEQUERYREQUEST = _descriptor.Descriptor(
  name='DescribeQueryRequest',
  full_name='Streaming.DescribeQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Streaming.DescribeQueryRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='request', full_name='Streaming.DescribeQueryRequest.request', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=820,
  serialized_end=965,
)


_DESCRIBEQUERYRESPONSE = _descriptor.Descriptor(
  name='DescribeQueryResponse',
  full_name='Streaming.DescribeQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Streaming.DescribeQueryResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=967,
  serialized_end=1036,
)

_INSTALLQUERYREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_INSTALLQUERYREQUEST.fields_by_name['request'].message_type = kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2._TINSTALLQUERYREQUEST
_INSTALLQUERYRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
_DELETEQUERYREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_DELETEQUERYREQUEST.fields_by_name['request'].message_type = kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2._TDELETEQUERYREQUEST
_DELETEQUERYRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
_LISTQUERIESREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_LISTQUERIESREQUEST.fields_by_name['request'].message_type = kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2._TLISTQUERIESREQUEST
_LISTQUERIESRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
_DESCRIBEQUERYREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_DESCRIBEQUERYREQUEST.fields_by_name['request'].message_type = kikimr_dot_streaming_dot_libs_dot_control__plane_dot_proto_dot_public_dot_control__plane__pb2._TDESCRIBEQUERYREQUEST
_DESCRIBEQUERYRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
DESCRIPTOR.message_types_by_name['InstallQueryRequest'] = _INSTALLQUERYREQUEST
DESCRIPTOR.message_types_by_name['InstallQueryResponse'] = _INSTALLQUERYRESPONSE
DESCRIPTOR.message_types_by_name['DeleteQueryRequest'] = _DELETEQUERYREQUEST
DESCRIPTOR.message_types_by_name['DeleteQueryResponse'] = _DELETEQUERYRESPONSE
DESCRIPTOR.message_types_by_name['ListQueriesRequest'] = _LISTQUERIESREQUEST
DESCRIPTOR.message_types_by_name['ListQueriesResponse'] = _LISTQUERIESRESPONSE
DESCRIPTOR.message_types_by_name['DescribeQueryRequest'] = _DESCRIBEQUERYREQUEST
DESCRIPTOR.message_types_by_name['DescribeQueryResponse'] = _DESCRIBEQUERYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

InstallQueryRequest = _reflection.GeneratedProtocolMessageType('InstallQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSTALLQUERYREQUEST,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.InstallQueryRequest)
  })
_sym_db.RegisterMessage(InstallQueryRequest)

InstallQueryResponse = _reflection.GeneratedProtocolMessageType('InstallQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSTALLQUERYRESPONSE,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.InstallQueryResponse)
  })
_sym_db.RegisterMessage(InstallQueryResponse)

DeleteQueryRequest = _reflection.GeneratedProtocolMessageType('DeleteQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETEQUERYREQUEST,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.DeleteQueryRequest)
  })
_sym_db.RegisterMessage(DeleteQueryRequest)

DeleteQueryResponse = _reflection.GeneratedProtocolMessageType('DeleteQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETEQUERYRESPONSE,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.DeleteQueryResponse)
  })
_sym_db.RegisterMessage(DeleteQueryResponse)

ListQueriesRequest = _reflection.GeneratedProtocolMessageType('ListQueriesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTQUERIESREQUEST,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.ListQueriesRequest)
  })
_sym_db.RegisterMessage(ListQueriesRequest)

ListQueriesResponse = _reflection.GeneratedProtocolMessageType('ListQueriesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTQUERIESRESPONSE,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.ListQueriesResponse)
  })
_sym_db.RegisterMessage(ListQueriesResponse)

DescribeQueryRequest = _reflection.GeneratedProtocolMessageType('DescribeQueryRequest', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEQUERYREQUEST,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.DescribeQueryRequest)
  })
_sym_db.RegisterMessage(DescribeQueryRequest)

DescribeQueryResponse = _reflection.GeneratedProtocolMessageType('DescribeQueryResponse', (_message.Message,), {
  'DESCRIPTOR' : _DESCRIBEQUERYRESPONSE,
  '__module__' : 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.DescribeQueryResponse)
  })
_sym_db.RegisterMessage(DescribeQueryResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
