# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/draft/streaming.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kikimr.public.api.protos import ydb_operation_pb2 as kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kikimr/public/api/protos/draft/streaming.proto',
  package='Streaming',
  syntax='proto3',
  serialized_pb=_b('\n.kikimr/public/api/protos/draft/streaming.proto\x12\tStreaming\x1a,kikimr/public/api/protos/ydb_operation.proto\"b\n\x13\x45xecuteQueryRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12\x10\n\x08yql_text\x18\x02 \x01(\t\"D\n\x14\x45xecuteQueryResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.Operation\"\'\n\x12\x45xecuteQueryResult\x12\x11\n\tresult_id\x18\x01 \x01(\tB*\n\x14\x63om.yandex.StreamingB\x0fStreamingProtos\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2.DESCRIPTOR,])




_EXECUTEQUERYREQUEST = _descriptor.Descriptor(
  name='ExecuteQueryRequest',
  full_name='Streaming.ExecuteQueryRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Streaming.ExecuteQueryRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='yql_text', full_name='Streaming.ExecuteQueryRequest.yql_text', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=205,
)


_EXECUTEQUERYRESPONSE = _descriptor.Descriptor(
  name='ExecuteQueryResponse',
  full_name='Streaming.ExecuteQueryResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Streaming.ExecuteQueryResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=207,
  serialized_end=275,
)


_EXECUTEQUERYRESULT = _descriptor.Descriptor(
  name='ExecuteQueryResult',
  full_name='Streaming.ExecuteQueryResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result_id', full_name='Streaming.ExecuteQueryResult.result_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=277,
  serialized_end=316,
)

_EXECUTEQUERYREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_EXECUTEQUERYRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
DESCRIPTOR.message_types_by_name['ExecuteQueryRequest'] = _EXECUTEQUERYREQUEST
DESCRIPTOR.message_types_by_name['ExecuteQueryResponse'] = _EXECUTEQUERYRESPONSE
DESCRIPTOR.message_types_by_name['ExecuteQueryResult'] = _EXECUTEQUERYRESULT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExecuteQueryRequest = _reflection.GeneratedProtocolMessageType('ExecuteQueryRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEQUERYREQUEST,
  __module__ = 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.ExecuteQueryRequest)
  ))
_sym_db.RegisterMessage(ExecuteQueryRequest)

ExecuteQueryResponse = _reflection.GeneratedProtocolMessageType('ExecuteQueryResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEQUERYRESPONSE,
  __module__ = 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.ExecuteQueryResponse)
  ))
_sym_db.RegisterMessage(ExecuteQueryResponse)

ExecuteQueryResult = _reflection.GeneratedProtocolMessageType('ExecuteQueryResult', (_message.Message,), dict(
  DESCRIPTOR = _EXECUTEQUERYRESULT,
  __module__ = 'kikimr.public.api.protos.draft.streaming_pb2'
  # @@protoc_insertion_point(class_scope:Streaming.ExecuteQueryResult)
  ))
_sym_db.RegisterMessage(ExecuteQueryResult)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\024com.yandex.StreamingB\017StreamingProtos\370\001\001'))
# @@protoc_insertion_point(module_scope)
