# -*- coding: utf-8 -*-
# flake8: noqa
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: draft/ydb_view_v1.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from ydb._grpc.v5.draft.protos import ydb_view_pb2 as draft_dot_protos_dot_ydb__view__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x64raft/ydb_view_v1.proto\x12\x0bYdb.View.V1\x1a\x1b\x64raft/protos/ydb_view.proto2\\\n\x0bViewService\x12M\n\x0c\x44\x65scribeView\x12\x1d.Ydb.View.DescribeViewRequest\x1a\x1e.Ydb.View.DescribeViewResponseB\\\n\x1ctech.ydb.proto.draft.view.v1Z9github.com/ydb-platform/ydb-go-genproto/draft/Ydb_View_V1\xf8\x01\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'draft.ydb_view_v1_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\034tech.ydb.proto.draft.view.v1Z9github.com/ydb-platform/ydb-go-genproto/draft/Ydb_View_V1\370\001\001'
  _VIEWSERVICE._serialized_start=69
  _VIEWSERVICE._serialized_end=161
# @@protoc_insertion_point(module_scope)
