# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/protos/ydb_export.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kikimr.public.api.protos import ydb_operation_pb2 as kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kikimr/public/api/protos/ydb_export.proto',
  package='Ydb.Export',
  syntax='proto3',
  serialized_pb=_b('\n)kikimr/public/api/protos/ydb_export.proto\x12\nYdb.Export\x1a,kikimr/public/api/protos/ydb_operation.proto\"\xb1\x01\n\x0e\x45xportProgress\"\x9e\x01\n\x08Progress\x12\x18\n\x14PROGRESS_UNSPECIFIED\x10\x00\x12\x16\n\x12PROGRESS_PREPARING\x10\x01\x12\x1a\n\x16PROGRESS_TRANSFER_DATA\x10\x02\x12\x11\n\rPROGRESS_DONE\x10\x03\x12\x19\n\x15PROGRESS_CANCELLATION\x10\x04\x12\x16\n\x12PROGRESS_CANCELLED\x10\x05\"\xda\x01\n\x12\x45xportToYtSettings\x12\x0c\n\x04host\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\r\x12\r\n\x05token\x18\x03 \x01(\t\x12\x32\n\x05items\x18\x04 \x03(\x0b\x32#.Ydb.Export.ExportToYtSettings.Item\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x19\n\x11number_of_retries\x18\x06 \x01(\r\x1a\x35\n\x04Item\x12\x13\n\x0bsource_path\x18\x01 \x01(\t\x12\x18\n\x10\x64\x65stination_path\x18\x02 \x01(\t\"\x12\n\x10\x45xportToYtResult\"}\n\x12\x45xportToYtMetadata\x12\x30\n\x08settings\x18\x01 \x01(\x0b\x32\x1e.Ydb.Export.ExportToYtSettings\x12\x35\n\x08progress\x18\x02 \x01(\x0e\x32#.Ydb.Export.ExportProgress.Progress\"\x80\x01\n\x11\x45xportToYtRequest\x12\x39\n\x10operation_params\x18\x01 \x01(\x0b\x32\x1f.Ydb.Operations.OperationParams\x12\x30\n\x08settings\x18\x02 \x01(\x0b\x32\x1e.Ydb.Export.ExportToYtSettings\"B\n\x12\x45xportToYtResponse\x12,\n\toperation\x18\x01 \x01(\x0b\x32\x19.Ydb.Operations.OperationB\x1a\n\x15\x63om.yandex.ydb.export\xf8\x01\x01\x62\x06proto3')
  ,
  dependencies=[kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2.DESCRIPTOR,])



_EXPORTPROGRESS_PROGRESS = _descriptor.EnumDescriptor(
  name='Progress',
  full_name='Ydb.Export.ExportProgress.Progress',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_UNSPECIFIED', index=0, number=0,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_PREPARING', index=1, number=1,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_TRANSFER_DATA', index=2, number=2,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_DONE', index=3, number=3,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_CANCELLATION', index=4, number=4,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='PROGRESS_CANCELLED', index=5, number=5,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=123,
  serialized_end=281,
)
_sym_db.RegisterEnumDescriptor(_EXPORTPROGRESS_PROGRESS)


_EXPORTPROGRESS = _descriptor.Descriptor(
  name='ExportProgress',
  full_name='Ydb.Export.ExportProgress',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _EXPORTPROGRESS_PROGRESS,
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=281,
)


_EXPORTTOYTSETTINGS_ITEM = _descriptor.Descriptor(
  name='Item',
  full_name='Ydb.Export.ExportToYtSettings.Item',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='source_path', full_name='Ydb.Export.ExportToYtSettings.Item.source_path', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='destination_path', full_name='Ydb.Export.ExportToYtSettings.Item.destination_path', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=449,
  serialized_end=502,
)

_EXPORTTOYTSETTINGS = _descriptor.Descriptor(
  name='ExportToYtSettings',
  full_name='Ydb.Export.ExportToYtSettings',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='host', full_name='Ydb.Export.ExportToYtSettings.host', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='port', full_name='Ydb.Export.ExportToYtSettings.port', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='Ydb.Export.ExportToYtSettings.token', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='items', full_name='Ydb.Export.ExportToYtSettings.items', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='description', full_name='Ydb.Export.ExportToYtSettings.description', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='number_of_retries', full_name='Ydb.Export.ExportToYtSettings.number_of_retries', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_EXPORTTOYTSETTINGS_ITEM, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=284,
  serialized_end=502,
)


_EXPORTTOYTRESULT = _descriptor.Descriptor(
  name='ExportToYtResult',
  full_name='Ydb.Export.ExportToYtResult',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=504,
  serialized_end=522,
)


_EXPORTTOYTMETADATA = _descriptor.Descriptor(
  name='ExportToYtMetadata',
  full_name='Ydb.Export.ExportToYtMetadata',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='settings', full_name='Ydb.Export.ExportToYtMetadata.settings', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='progress', full_name='Ydb.Export.ExportToYtMetadata.progress', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=524,
  serialized_end=649,
)


_EXPORTTOYTREQUEST = _descriptor.Descriptor(
  name='ExportToYtRequest',
  full_name='Ydb.Export.ExportToYtRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_params', full_name='Ydb.Export.ExportToYtRequest.operation_params', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='settings', full_name='Ydb.Export.ExportToYtRequest.settings', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=652,
  serialized_end=780,
)


_EXPORTTOYTRESPONSE = _descriptor.Descriptor(
  name='ExportToYtResponse',
  full_name='Ydb.Export.ExportToYtResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation', full_name='Ydb.Export.ExportToYtResponse.operation', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=782,
  serialized_end=848,
)

_EXPORTPROGRESS_PROGRESS.containing_type = _EXPORTPROGRESS
_EXPORTTOYTSETTINGS_ITEM.containing_type = _EXPORTTOYTSETTINGS
_EXPORTTOYTSETTINGS.fields_by_name['items'].message_type = _EXPORTTOYTSETTINGS_ITEM
_EXPORTTOYTMETADATA.fields_by_name['settings'].message_type = _EXPORTTOYTSETTINGS
_EXPORTTOYTMETADATA.fields_by_name['progress'].enum_type = _EXPORTPROGRESS_PROGRESS
_EXPORTTOYTREQUEST.fields_by_name['operation_params'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATIONPARAMS
_EXPORTTOYTREQUEST.fields_by_name['settings'].message_type = _EXPORTTOYTSETTINGS
_EXPORTTOYTRESPONSE.fields_by_name['operation'].message_type = kikimr_dot_public_dot_api_dot_protos_dot_ydb__operation__pb2._OPERATION
DESCRIPTOR.message_types_by_name['ExportProgress'] = _EXPORTPROGRESS
DESCRIPTOR.message_types_by_name['ExportToYtSettings'] = _EXPORTTOYTSETTINGS
DESCRIPTOR.message_types_by_name['ExportToYtResult'] = _EXPORTTOYTRESULT
DESCRIPTOR.message_types_by_name['ExportToYtMetadata'] = _EXPORTTOYTMETADATA
DESCRIPTOR.message_types_by_name['ExportToYtRequest'] = _EXPORTTOYTREQUEST
DESCRIPTOR.message_types_by_name['ExportToYtResponse'] = _EXPORTTOYTRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ExportProgress = _reflection.GeneratedProtocolMessageType('ExportProgress', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTPROGRESS,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportProgress)
  ))
_sym_db.RegisterMessage(ExportProgress)

ExportToYtSettings = _reflection.GeneratedProtocolMessageType('ExportToYtSettings', (_message.Message,), dict(

  Item = _reflection.GeneratedProtocolMessageType('Item', (_message.Message,), dict(
    DESCRIPTOR = _EXPORTTOYTSETTINGS_ITEM,
    __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
    # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtSettings.Item)
    ))
  ,
  DESCRIPTOR = _EXPORTTOYTSETTINGS,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtSettings)
  ))
_sym_db.RegisterMessage(ExportToYtSettings)
_sym_db.RegisterMessage(ExportToYtSettings.Item)

ExportToYtResult = _reflection.GeneratedProtocolMessageType('ExportToYtResult', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTTOYTRESULT,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtResult)
  ))
_sym_db.RegisterMessage(ExportToYtResult)

ExportToYtMetadata = _reflection.GeneratedProtocolMessageType('ExportToYtMetadata', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTTOYTMETADATA,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtMetadata)
  ))
_sym_db.RegisterMessage(ExportToYtMetadata)

ExportToYtRequest = _reflection.GeneratedProtocolMessageType('ExportToYtRequest', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTTOYTREQUEST,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtRequest)
  ))
_sym_db.RegisterMessage(ExportToYtRequest)

ExportToYtResponse = _reflection.GeneratedProtocolMessageType('ExportToYtResponse', (_message.Message,), dict(
  DESCRIPTOR = _EXPORTTOYTRESPONSE,
  __module__ = 'kikimr.public.api.protos.ydb_export_pb2'
  # @@protoc_insertion_point(class_scope:Ydb.Export.ExportToYtResponse)
  ))
_sym_db.RegisterMessage(ExportToYtResponse)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\025com.yandex.ydb.export\370\001\001'))
# @@protoc_insertion_point(module_scope)
