# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kikimr/public/api/grpc/draft/yql_db_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from kikimr.public.api.protos.draft import yql_internal_pb2 as kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kikimr/public/api/grpc/draft/yql_db_v1.proto',
  package='Yql.Analytics.V1',
  syntax='proto3',
  serialized_options=b'\n\036com.yandex.yql.analytics.db.v1',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n,kikimr/public/api/grpc/draft/yql_db_v1.proto\x12\x10Yql.Analytics.V1\x1a\x31kikimr/public/api/protos/draft/yql_internal.proto2\x91\x02\n\x16YqlInternalTaskService\x12H\n\x07GetTask\x12\x1d.Yql.Analytics.GetTaskRequest\x1a\x1e.Yql.Analytics.GetTaskResponse\x12K\n\x08PingTask\x12\x1e.Yql.Analytics.PingTaskRequest\x1a\x1f.Yql.Analytics.PingTaskResponse\x12`\n\x0fWriteTaskResult\x12%.Yql.Analytics.WriteTaskResultRequest\x1a&.Yql.Analytics.WriteTaskResultResponseB \n\x1e\x63om.yandex.yql.analytics.db.v1b\x06proto3'
  ,
  dependencies=[kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2.DESCRIPTOR,])



_sym_db.RegisterFileDescriptor(DESCRIPTOR)


DESCRIPTOR._options = None

_YQLINTERNALTASKSERVICE = _descriptor.ServiceDescriptor(
  name='YqlInternalTaskService',
  full_name='Yql.Analytics.V1.YqlInternalTaskService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=118,
  serialized_end=391,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetTask',
    full_name='Yql.Analytics.V1.YqlInternalTaskService.GetTask',
    index=0,
    containing_service=None,
    input_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._GETTASKREQUEST,
    output_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._GETTASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PingTask',
    full_name='Yql.Analytics.V1.YqlInternalTaskService.PingTask',
    index=1,
    containing_service=None,
    input_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._PINGTASKREQUEST,
    output_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._PINGTASKRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='WriteTaskResult',
    full_name='Yql.Analytics.V1.YqlInternalTaskService.WriteTaskResult',
    index=2,
    containing_service=None,
    input_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._WRITETASKRESULTREQUEST,
    output_type=kikimr_dot_public_dot_api_dot_protos_dot_draft_dot_yql__internal__pb2._WRITETASKRESULTRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_YQLINTERNALTASKSERVICE)

DESCRIPTOR.services_by_name['YqlInternalTaskService'] = _YQLINTERNALTASKSERVICE

# @@protoc_insertion_point(module_scope)
